export const returnCodes = new Map([
    // Successful completion
    [0, "Successful completion."],
    [1, "Successful completion with no information returned."],
  
    // Common errors
    [2, "Common error."],
    [3, "Invalid parameters."],
    [4, "Invalid information."],
    [5, "Hard disk error."],
    [6, "Memory error."],
    [7, "Network error."],
    [8, "Not enough permissions to perform the operation."],
    [9, "Timeout expired."],
    [10, "No connection."],
    [11, "Service is not available."],
    [12, "Too frequent requests."],
    [13, "Not found."],
    [14, "Partial error."],
    [15, "Server shutdown in progress."],
    [16, "The operation has been canceled."],
    [17, "Duplicate information."],
  
    // User management
    [3001, "The last administrator account has been deleted."],
    [3002, "The range of logins has been exhausted."],
    [3003, "The login is reserved on another server."],
    [3004, "The account already exists."],
    [3005, "An attempt of self-deletion."],
    [3006, "Incorrect account password."],
    [3007, "Reached the limit on the number of users."],
    [3008, "The accounts has open positions."],
    [3009, "An attempt to move an account to another server."],
    [
      3010,
      "An attempt to move an accounts to a group with a different deposit currency.",
    ],
    [3011, "Failed to import account balance."],
    [3012, "The account is imported with the wrong group."],
    [
      3013,
      "A trading account in an external system already exists for a specified login.",
    ],
    [3014, "Failed to import account's trading data."],
    [3015, "Failed to import account's trading positions."],
    [3016, "Failed to import account's open orders."],
    [3017, "Failed to import account's deal history."],
    [3018, "Failed to import account's order history."],
  
    // Trade Requests
    [10001, "Request is on the way."],
    [10002, "Request accepted."],
    [10003, "Request processed."],
    [10004, "Requote in response to the request."],
    [10005, "Prices in response to the request."],
    [10006, "Request rejected."],
    [10007, "Request canceled."],
    [10008, "An order placed as a result of the request."],
    [10009, "Request fulfilled."],
    [10010, "Request partially fulfilled."],
    [10011, "Common error of request."],
    [10012, "Request timed out."],
    [10013, "Invalid request."],
    [10014, "Invalid volume."],
    [10015, "Invalid price."],
    [10016, "Wrong stop levels or price."],
    [10017, "Trade is disabled."],
    [10018, "Market is closed."],
    [10019, "Not enough money."],
    [10020, "Price has changed."],
    [10021, "No price."],
    [10022, "Invalid order expiration."],
    [10023, "Order has been changed."],
    [
      10024,
      "Too many trade requests. For example, this error can be returned in response to an attempt to send more than 128 trade requests from one Manager API instance.",
    ],
    [10025, "Request does not contain changes."],
    [10026, "Autotrading disabled on the server."],
    [10027, "Autotrading disabled on the client side."],
    [10028, "Request blocked by the dealer."],
    [
      10029,
      "Modification failed due to order or position being close to market.",
    ],
    [10030, "Fill mode is not supported."],
    [10031, "No connection."],
    [10032, "Allowed only for real accounts."],
    [10033, "Reached the limit on the number of orders."],
    [10034, "Reached the volume limit."],
    [10035, "Invalid or prohibited order type."],
    [
      10036,
      "Position is already closed. For example, this error appears when attempting to modify the stop levels of an already closed position.",
    ],
    [10037, "Used for internal purposes."],
    [10038, "Volume to be closed exceeds the current volume of the position."],
    [
      10039,
      '"Order to close the position already exists. The error may appear in the hedging mode: when trying to closed a position with an opposite one in case there\'s already an order to close that position when trying to close the entire position or a part of it in case the total volume of existing orders to close it and the newly placed order exceeds the current volume of the position"',
    ],
    [
      10040,
      '"The number of open positions simultaneously present on an account can be limited by the settings of a group. After a limit is reached, the server returns the MT_TRADE_RETCODE_REQUEST_LIMIT_POSITIONS error when attempting to place an order. The limitation operates differently depending on the position accounting type: Netting — number of open positions is considered. When a limit is reached, the platform disables placing new orders whose execution may increase the number of open positions. In fact, the platform allows placing orders only for the symbols that already have open positions. The current pending orders are not considered since their execution may lead to changes in the current positions but it cannot increase their number. Hedging — pending orders are considered together with open positions, since a pending order activation always leads to opening a new position. When a limit is reached, the platform disables placing both new market orders for opening positions and pending orders."',
    ],
    [
      10041,
      "Request rejected, order canceled. This code is returned when the action IMTConRoute::ACTION_CANCEL_ORDER in a routing rule is applied.",
    ],
    [
      10042,
      'The request is rejected, because the "Only long positions are allowed" rule is set for the symbol (IMTConSymbol::TRADE_LONGONLY).',
    ],
    [
      10043,
      'The request is rejected, because the "Only short positions are allowed" rule is set for the symbol (IMTConSymbol::TRADE_SHORTONLY).',
    ],
    [
      10044,
      'The request is rejected, because the "Only position closing is allowed" rule is set for the symbol (IMTConSymbol::TRADE_CLOSEONLY).',
    ],
    [
      10045,
      "Position closure is not allowed by the FIFO rule. It is used for the groups with the enabled IMTConGroup::TRADEFLAGS_FIFO_CLOSE option, according to which all positions should be closed strictly in the order in which they were opened: the oldest one should be closed first, then the next one, etc.",
    ],
    [
      10046,
      "Opening of a position or placing of a pending order is not possible because hedge positions are prohibited. The error is returned if a user tries to execute a trading operation in the case the IMTConGroup::TRADEFLAGS_HEDGE_PROHIBIT flag is enabled for the group and the user already has an opposite order or position for the same symbol.",
    ],
  ]);